# Generated by Django 6.1.1 on 2026-09-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='city',
            field=models.CharField(default='Jakarta', max_length=100),
        ),
        migrations.AddField(
            model_name='concert',
            name='genre',
            field=models.CharField(default='Pop', max_length=50),
        ),
    ]
