# Generated by Django 6.1.1 on 2026-09-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_concert_city_concert_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='concert_posters/'),
        ),
    ]
